configuration: Release

init:
  - cmd: set
  
install:
  - cmd: choco install gitversion.portable -pre -y
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
     
before_build:
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
  - cmd: nuget restore Zeroconf.sln
  - cmd: gitversion /l console /output buildserver /updateAssemblyInfo
  
build:
  verbosity: normal
  parallel: true
  project: Zeroconf.sln
  
after_build:
  - ps: '.\packages\gitlink\lib\net45\GitLink.exe . -f Zeroconf.sln -u https://github.com/onovotny/Zeroconf -s $env:APPVEYOR_REPO_COMMIT;if($lastexitcode -ne 0){$lastexitcode = 0}'
  - cmd: nuget pack nuget\Zeroconf.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -NoPackageAnalysis
  - cmd: appveyor PushArtifact "Zeroconf.%GitVersion_NuGetVersion%.nupkg"  
  
